literalGsub: Robustness: Complain about newlines in FROM-TEXT and handle in TO-TEXT
sed is line-based.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: sed (GNU sed) 4.7

diff --git a/bin/literalGsub b/bin/literalGsub
--- a/bin/literalGsub
+++ b/bin/literalGsub
@@ -22,6 +22,10 @@ do
 			sedArgs+=("$1"); shift;;
 	--from-to|-e)	shift
 			literalPattern="${1:?}"; shift
+			if [[ "$literalPattern" =~ $'\n' ]]; then
+			    echo >&2 'ERROR: FROM-TEXT must not contain newlines.'
+			    exit 2
+			fi
 			literalPattern="${literalPattern//\\/\\\\}"
 			literalPattern="${literalPattern//\[/\\\[}"
 			literalPattern="${literalPattern//\]/\\\]}"
@@ -33,6 +37,7 @@ do
 			literalReplacement="${1?}"; shift
 			literalReplacement="${literalReplacement//\\/\\\\}"
 			literalReplacement="${literalReplacement//&/\\&}"
+			literalReplacement="${literalReplacement//$'\n'/\\n}"
 
 			sedSubstitutions+=(-e "s#${literalPattern//#/\\#}#${literalReplacement//#/\\#}#g")
 			;;
